Repository prgrms-fullstack-devcourse/Comeet_FE, pull requests merged in 2025-08, with the labels that each got.

#8 Feature: 커뮤니티 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/avatar.tsx
  src/components/ui/separator.tsx
  src/hooks/usePost.ts
  src/main.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/community/PostDetailPage.tsx
  src/pages/community/__components/CommentForm.tsx
  src/pages/community/__components/CommentItem.tsx
  src/pages/community/__components/CommentSection.tsx
  src/pages/community/__components/PostContent.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/search/index.tsx
  src/types/community.ts
Labels: ✨feature, 🐞bugfix, 🎨style

#10 Feature: GitHub OAuth 2.0 로그인 시스템 구현 및 React Query 도입
  .gitignore
  package-lock.json
  package.json
  src/hooks/useGitHubCallback.ts
  src/lib/api.ts
  src/main.tsx
  src/pages/auth/AuthCallbackPage.tsx
  src/pages/auth/LoginPage.tsx
  src/types/auth.ts
Labels: ✨feature, 🐞bugfix, 🔄refactor, ⚙️chore

#11 Style: UI 수정
  src/App.tsx
  src/components/common/ModalWrapper.tsx
  src/components/common/PositionSelector.tsx
  src/components/common/StackSelector.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/GlobalLayout.tsx
  src/components/layout/Header.tsx
  src/components/ui/button.tsx
  src/components/ui/separator.tsx
  src/constants/.gitkeep
  src/constants/navigation.ts
  src/hooks/.gitkeep
  src/hooks/useAddPostModal.ts
  src/hooks/usePost.ts
  src/index.css
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/chat/index.tsx
  src/pages/community/PostDetailPage.tsx
  src/pages/community/__components/CommentForm.tsx
  src/pages/community/__components/CommentItem.tsx
  src/pages/community/__components/CommentSection.tsx
  src/pages/community/__components/PostContent.tsx
  src/pages/community/__components/ReplyItem.tsx
  src/pages/developer/index.tsx
  src/pages/explore/_components/FilteringModal.tsx
  src/pages/explore/index.tsx
  src/pages/home/_components/ListItem.tsx
  src/pages/home/_components/modal/AddPostModal.tsx
  src/pages/home/_components/modal/PostItem.tsx
  src/pages/home/_components/modal/RecruitItem.tsx
  src/pages/home/index.tsx
  src/pages/my/index.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/__components/OnboardingStep1.tsx
  src/pages/onboarding/__components/OnboardingStep2.tsx
  src/pages/onboarding/__components/OnboardingStep3.tsx
  src/pages/onboarding/__components/OnboardingStep4.tsx
  src/pages/search/_components/RecentSearchList.tsx
  src/pages/search/_components/SearchHeader.tsx
  src/pages/search/index.tsx
  src/types/community.ts
Labels: ✨feature, 🐞bugfix, 🔄refactor, 🎨style
